# Use postgres/example user/password credentials
version: '3.7'

services:
  nestjs-rabbitmq:
    container_name: nestjs-rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: rodacapera@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db
